:PROPERTIES:
:ID:       d6853f9e-c807-42ea-bfa7-a8488540d545
:END:
#+title:     Exercícios para a prova
#+EMAIL:     gabrielamoreira05@gmail.com
#+DATE:      24 de abril de 2024
#+LANGUAGE:  en
#+OPTIONS:    toc:t
#+LaTeX_CLASS: bugarela-article
#+LATEX_COMPILER: pdflatex
#+LATEX_HEADER:  \usepackage[margin=2cm]{geometry} \usepackage{enumitem} \setlist{noitemsep, topsep=0pt}
#+cite_export: csl ~/MEGA/csl/associacao-brasileira-de-normas-tecnicas.csl

* Estruturas de Kripke
1. Identifique em quais estruturas de Kripke a seguir tem não-determinismo e justifique sua resposta.
   a) Semáforos
        #+begin_src mermaid :file 1a.png :theme neutral :width 400px :background-color transparent
        stateDiagram
            direction LR
            vermelho --> verde
            verde --> amarelo
            amarelo --> vermelho
        #+end_src
   b) Chaleira
       #+begin_src mermaid :file 2b.png :theme neutral :width 400px :background-color transparent
       stateDiagram
         direction LR
         temperatura_ambiente --> esquentando
         esquentando --> esfriando
         esfriando --> esquentando
         cem_graus --> esfriando
         esfriando --> temperatura_ambiente
         esquentando --> cem_graus
       #+end_src
2. Defina uma estrutura de Kripke para um sistema de caixa da água com as seguintes características:
   - A caixa da água contém uma bóia que impede que ela transborde, ou seja, a bóia interrompe o enchimento quando a caixa está completamente cheia.
   - A caixa não enche enquanto está sendo usada, ou seja, ela não pode estar enchendo e esvaziando ao mesmo tempo.
   - Se a caixa está vazia, ela não pode ser esvaziada.
   PS: Tente usar o mínimo de estados e transições necessários para representar esse sistema.

* Lógica temporal
1. Dada uma fórmula temporal e uma execução, indique se a fórmula é verdadeira ou falsa para a execução. Ou seja, responda verdadeiro se a execução satisfaz a fórmula e falso caso não satisfaça. Considere que $a$ e $b$ são proposições.

   a) Fórmula: $X(b)$
      - [ ] $[b], [b], [a]$
      - [ ] $[a], [b], [a]$
      - [ ] $[a], [a], [b]$
   b) Fórmula: $a -> b$
      - [ ] $[a], [a], [a]$
      - [ ] $[a], [b], [a]$
      - [ ] $[a, b], [a], [a]$
      - [ ] $[b], [a], [a]$
   c) Fórmula: $F(a)$
      - [ ] $[a], [a], [a]$
      - [ ] $[b], [a], [b]$

2. Explique a diferença entre LTL (Lógica Temporal Linear) e CTL (Lógica de árvore computacional - /Computational Tree Logic/).

# * TLA+ e Quint
# - Match entre spec e descrição em português
# - Dada uma execução X, a especificação aceita?
# - Dada uma definição/especificação, onde há não-determinismo?
# - Fill blanks

* Propriedades
# - Qual das fórmulas abaixo pode ser uma invariante?
1. Assinale as fórmulas abaixo com [I] - Invariante ou [V] - Vivacidade (Propriedade de Vivacidade ou /Liveness Property/). Lembre-se que não importa se a fórmula é verdadeira ou falsa.
  - [ ] Para cada compra no cartão de crédito, vem uma cobrança na fatura ao final do mês.
  - [ ] Nunca vou para a academia sem meus fones de ouvido
  - [ ] Em algum momento vou terminar de pagar as parcelas do meu apartamento
  - [ ] Sempre uso óculos para dirigir
  - [ ] Não é possível estar na aula e no shopping ao mesmo tempo
  - [ ] Todos os códigos em C++ serão migrados para Rust

* Assumptions
1. Alice e Bob estavam combinando de se encontrar e Alice mandou a seguinte mensagem para Bob: "Encontre-me as 15h na cafeteria Café Quentinho". Ao fazer essa comunicação, Alice estava supondo algumas coisas. Descreva qual suposição de Alice estava errada para cada um dos cenários a seguir.
   a) Bob não apareceu. A bateria do celular dele acabou antes que visse a mensagem de Alice.
        Responda: Alice assumiu que ...
        # > Alice assumiu que Bob havia recebido a mensagem dela.
   b) Bob foi em outro Café Quentinho - acontece que havia outra cafeteria com esse nome em outro bairro.
        Responda: Alice assumiu que ...
        # > Alice assumiu que havia apenas uma "Café Quentinho" na cidade
   c) Quando Alice chegou, o Bob já estava lá por uma hora. Ele havia esquecido de ajustar seu relógio no fim do horário de verão.
        Responda: Alice assumiu que ...
        # > Alice assumiu que o relógio de Bob estava no mesmo horário que o seu.


* Perguntas gerais
1. Suponha que temos um modelo e uma propriedade que é violada numa execução de 5 passos. Considere que estamos usando um simulador aleatório com até 10.000 amostras e 10 passos, e um /model checker/ com até 10 passos. Assinale com verdadeiro ou falso *e justifque sua resposta*.
  - [ ] O simulador irá encontar um contraexemplo para propriedades
  - [ ] O /model checker/ encontrará um contraexemplo de 5 passos
  - [ ] O /model checker/ demorará mais tempo que o simulador para responder
  - [ ] O simulador demorará mais tempo que o /model checker/ para responder
  - [ ] O /model checker/ poderá finalizar a execução sem encontrar o contraexemplo
  - [ ] O simulador pode encontrar um contraexemplo de 9 passos
