:PROPERTIES:
:ID:       00beb988-69bf-4868-83b5-1f3353b9b014
:END:
#+title:  Especificar vs Implementar
#+EMAIL:     gabrielamoreira05@gmail.com
#+DATE:      22 de abril de 2024
#+LANGUAGE:  en
#+OPTIONS:   H:2 num:t toc:nil \n:t @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:nil pri:nil tags:not-in-toc
#+BEAMER_FRAME_LEVEL: 2
#+startup: beamer
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [smaller]
#+BEAMER_THEME: udesc
#+BEAMER_HEADER: \input{header.tex} \subtitle{Aula para disciplina de Métodos Formais} \institute{Departamento de Ciência da Computação - DCC\\Universidade do Estado de Santa Catarina - UDESC}
#+LATEX_COMPILER: pdflatex
#+bibliography: references.bib
#+cite_export: csl ~/MEGA/csl/associacao-brasileira-de-normas-tecnicas.csl
#+PROPERTY: header-args :tangle tictactoe.tla
#+HTML: <a href="https://bugarela.com/mfo/slides/20240422102646-mfo_especificar_vs_implementar.pdf">Slides</a><br />
#+beamer: \begin{frame}{Conteúdo}
#+TOC: headlines 3
#+beamer: \end{frame}

* Exercício Pokemons
** Exercício Pokemons
- Primeiros 20min de aula serão para vocês continuarem o exercício
  - Objetivo principal é que lembrem onde estavam, qual era a dificuldade, dúvidas, etc.
  - Se alguém terminou, pode me chamar para ter feedback da solução

- Depois, veremos uma sugestão de resolução.

* Especificar vs Implementar
** Por que estamos escrevendo uma especificação para um jogo de pokemon?
Para que a especificação *não* serve:
#+BEAMER: \pause
- Para jogar pokemon
  #+BEAMER: \pause
  - Não temos input/output pros jogadores
#+BEAMER: \pause
- Para analisar o balanceamento (i.e. Charmander ganha do Squirtle 40% das vezes)
  #+BEAMER: \pause
  - Quint e TLA+ não fazem análise estatística

#+BEAMER: \medskip
#+BEAMER: \pause
Para que ela *serve*:
- Explicar pokemon pra quem não conhece pokemon
  #+BEAMER: \pause
  - A especificação em si é uma descrição precisa do que pode acontecer e do que é esperado
  - Usando simulação ou /model checking/, podemos obter execuções exemplo que ajudam no entendimento
#+BEAMER: \pause
- Verificar propriedades
  #+BEAMER: \pause
  - Verificar que algo desejável pode acontecer (i.e. é possível um pokemon ficar zero ou menos de vida)
  - Verficar que algo importante é verdade *sempre* (i.e. usando uma estratégia, o Squirte sempre vence o Charmander)
   # Como isso pode ser importante? Disciplina: Estratégias de pokemon. Questão de prova: Use a estratégia X para derrotar o Charmander. A professora precisa garantir que isso sempre vai funcionar.

** Mas por que só não implementar e simular?
Por que só não fazemos isso em [insira linguagem de programação] e usamos um laço de repetição para testar N (ou todos) os cenários?

#+BEAMER: \medskip
#+BEAMER: \pause
Porque:
- Quint/TLA+ tem restrições para que seja possível fazer /model checking/
- O simulador é reutilizável, com toda a estratégia de simulação e interface

#+BEAMER: \medskip
#+BEAMER: \pause
Ah, mas se eu fizer em [insira linguagem de programação], eu já posso usar o programa para jogar também.
#+BEAMER: \pause
- Para isso, seria necessário cuidar da distribuição/autorização dos jogadores
  - Jogador 1 só pode escolher os ataques do time A, e jogador 2 só pode escolher os ataques do time B
  - Isso diminui o nível de abstração, e pode tornar aquilo que é mais importante mais difícil de compreender.

** Motivação para o trabalho
#+BEAMER: \pause
- O principal motivo para o exercício de pokemons foi trabalhar em um contexto semelhante ao do nosso primeiro trabalho, que envolverá jogos de RPG de mesa.
#+BEAMER: \pause
- Com algumas regras de RPG, conseguimos alguns problemas análogos aos problemas de sistemas distribuídos, campo onde métodos formais são melhor empregados.
  #+BEAMER: \pause
  - Jogos em si não são um bom exemplo por conta da falta de impacto (risco = impacto x ameaça). Geralmente as empresas investem em usar métodos formais onde o impacto de possíveis problemas é muito alto.
  #+BEAMER: \pause
  - Depois de passar o trabalho, vou explicar um pouco essas analogias. Uma analogia que se aplica ao jogo da velha e ao pokemon: estratégias podem ser vistas como protocolos. Protocolos definem passos que devem acontecer em cada cenário com objetivo de garantir alguma coisa.

** Protocolos
Exemplos de protocolos:
  #+BEAMER: \pause
  - Entregar a prova de cabeça pra baixo e pedir que todos desvirem no mesmo momento é uma forma de garantir que todos tem o mesmo tempo de prova
  #+BEAMER: \pause
  - Na decolagem/pouso de um avião, precisamos abrir as janelas e levantar as mesinhas
  #+BEAMER: \pause
  - Sistemas de trocas em jogos ou, semelhantemente, sistemas de pagamento estilo mercado pago

#+BEAMER: \medskip
#+BEAMER: \pause
Podemos entender protocolos como estratégias para garantir ou impedir que algo aconteça.

#+BEAMER: \medskip
#+BEAMER: \pause
Podemos entender estratégias de jogo como um protocolo que leva à vitória.

** FIM
#+BEAMER: \maketitle
