#+TITLE: 

* Links úteis
  - [[file:20240210123703-mfo_apresentacao.org][Apresentação]]
  - [[https://bugarela.com/mfo/cheatsheet_logica_temporal.pdf][Cheatsheet Lógica Temporal (PDF)]]
  - [[file:20240525134648-mfo_exercicios_para_a_prova.org][Exercícios para a prova]]
* Aulas
  - [[file:20240213151141-mfo_programacao_e_matematica_nao_sao_a_mesma_coisa.org][Programação e matemática não são a mesma coisa]]
  - [[file:20240217142930-mfo_estruturas_de_kripke.org][Estruturas de Kripke]]
  - [[file:20240303165631-mfo_logica_temporal.org][Checando propriedades com Lógica Temporal]]
  - [[file:20240306214020-mfo_logica_temporal_2.org][Checando propriedades com Lógica Temporal II]]
  - [[file:20240310185059-por_que_e_pra_que_metodos_formais.org][Por que e pra que métodos formais?]]
  - [[file:20240319195624-mfo_logica_temporal_das_acoes.org][Introdução à Lógica Temporal das Ações]]
#   - [[file:20240322161707-mfo_primeiras_especificacoes.org][Primeiras Especificações]]
#   - [[file:20240324195706-mfo_revisao_de_programacao_funcional.org][Revisão de programação funcional em Quint]]
#   - [[file:20240330105337-mfo_jogo_da_velha_em_quint.org][Jogo da Velha em Quint]]
#   - [[file:20240331223036-mfo_introducao_ao_tla.org][Introdução ao TLA+]]
#   - [[file:20240408201756-mfo_primeiras_especificacoes_em_tla.org][Primeiras Especificações em TLA+]]
#   - [[file:20240415205323-mfo_exercicios_pokemon.org][Exercícios Pokemon]]
#   - [[file:20240422102646-mfo_especificar_vs_implementar.org][Especificar vs Implementar]]
#   - [[file:20240507182006-mfo_efetivacao_em_duas_fases.org][Efetivação em Duas Fases]]
#   - [[file:20240504145616-mfo_design_de_protocolos.org][Design de protocolos]]
#   - [[file:20240511143312-mfo_propriedades.org][Propriedades]]
#   - [[file:20240520131408-mfo_testando_um_problema_da_maratona.org][Testando um problema da maratona]]
#   - [[file:20240623102850-mfo_model_checking.org][Model Checking]]
#   - [[file:20240625203536-mfo_tla_avancado.org][TLA+ Avançado]]
# * Trabalho 1
#   - [[file:20240423183852-mfo_trabalho_1.org][Trabalho 1]]
#   - [[file:20240517155753-mfo_faq_trabalho_1.org][FAQ Trabalho 1]]
#   - [[file:20240424144115-mfo_dicas_trabalho_1.org][Dicas Trabalho 1]]
* Seminário
  - [[file:20240531080208-mfo_seminario.org][Seminário]]
# * Trabalho 2
#   - [[file:20240609214243-mfo_trabalho_2.org][Trabalho 2]]
