#+TITLE: 

- [[file:20240210123703-mfo_apresentacao.org][Apresentação]]
- [[file:20240213151141-mfo_programacao_e_matematica_nao_sao_a_mesma_coisa.org][Programação e matemática não são a mesma coisa]]
- [[file:20240217142930-mfo_estruturas_de_kripke.org][Estruturas de Kripke]]
- [[file:20240303165631-mfo_logica_temporal.org][Checando propriedades com Lógica Temporal]]
- [[file:20240306214020-mfo_logica_temporal_2.org][Checando propriedades com Lógica Temporal II]]
- [[file:20240310185059-por_que_e_pra_que_metodos_formais.org][Por que e pra que métodos formais?]]