(dolist (d '("docs" "images"))
  (unless (file-exists-p d)
    (make-directory d)))

(org-babel-tangle)
;; (org-publish-remove-all-timestamps)
;;
(defvar personal-site-full-name "Gabriela Moreira"
  "A string with your full name.")

(defvar personal-site-position "Formal methods & programming languages research engineer"
  "A string with your full position or job appointment.")

(defvar personal-site-github "bugarela"
  "If not NIL, your GitHub id.")

(defvar personal-site-google-scholar-id nil
  "If not NIL, your Google Scholar id.")

(defvar personal-site-email nil
  "If not NIL, your Google Scholar id.")

(defvar personal-site-linkedin "bugarela"
  "If not NIL, your Linkedin id.")

(defvar personal-site-organization nil
  "If not NIL, a string with the name of your organization, without the @ sign.")

(defvar personal-site-organization-url nil
  "If not NIL, the URL of your organization.")

(defvar personal-site-twitter "bugarela"
  "If not NIL, a string with a Twitter handle, without the @ sign.")

(setq org-publish-project-alist
      `(("lectures-mfo"
         :base-directory ,(expand-file-name "./mfo")
         :root-directory ,(expand-file-name "./")
         ;; :recursive t
         :base-extension "org"
         :publishing-directory ,(expand-file-name "./docs/mfo")
         ;; Exclude the blog archive index autogenerated below
         ;; Note that the regexp is relative to :base-directory
         :exclude "^index.org"
         :section-numbers nil
         :language "pt_BR"
         :with-toc t
         :with-date t
         :html-template ,(ox-thtml-load-template "templates/mfo.html")
         :publishing-function ox-thtml-publish
         :auto-sitemap t
         :sitemap-folders ignore
         :sitemap-style list
         :sitemap-title ""
         :sitemap-filename "sitemap.inc"
         :sitemap-sort-files chronologically
         )
        ("homepage-mfo"
         :base-directory ,(expand-file-name "./mfo")
         :root-directory ,(expand-file-name "./")
         ;; :recursive t
         :base-extension "org"
         :publishing-directory ,(expand-file-name "./docs/mfo")
         ;; Exclude the blog archive index autogenerated below
         ;; Note that the regexp is relative to :base-directory
         ;; :exclude "^index.org"
         :section-numbers nil
         :language "pt_BR"
         :with-toc t
         :with-date t
         :html-template ,(ox-thtml-load-template "templates/mfo.html")
         :publishing-function ox-thtml-publish
         )
        ("homepage-pages"
         :base-directory ,(expand-file-name "./")
         ;; :recursive t
         :base-extension "org"
         ;; :include ("blog/index.org")
         :exclude ,(regexp-opt '("mfo"))
         :publishing-directory ,(expand-file-name "./docs")
         :section-numbers nil
         :language "pt_BR"
         :with-toc nil
         :with-date nil
         :html-template ,(ox-thtml-load-template "templates/index.html")
         :publishing-function ox-thtml-publish
         )
        ("homepage-assets"
         :base-directory "./"
         :publishing-directory "./docs"
         ;; :recursive t
         :language "pt_BR"
         :exclude "^\\(docs\\|templates\\).*"
         :base-extension "\\(ico\\|jpg\\|gif\\|png\\|css\\|js\\|el\\|nb\\|ipynb\\|pdf\\|xml\\|zip\\)"
         :publishing-function org-publish-attachment)
        ("homepage" :components ("lectures-mfo" "homepage-mfo" "homepage-pages"
                                 "homepage-assets"))
        ))

(let ((enable-local-variables :all)
      (find-file-hook nil))
  (org-publish "homepage" t))

(ox-thtml-create-sitemap-xml "docs/sitemap.xml" "docs" ox-thtml-site-url)
